---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-test-1-cert
  namespace: app-test-1
spec:
  secretName: app-test-1-tls-secret
  issuerRef:
    name: ssl-issuer
    kind: ClusterIssuer
  dnsNames:
    - app1.lazylab.page